# Generated by Django 3.2.7 on 2021-09-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hudud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Razryad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razryad_nomi', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportturi', models.CharField(max_length=212)),
            ],
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashkilot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(null=True)),
                ('full_name', models.CharField(blank=True, max_length=156, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('Passport', models.CharField(max_length=45, null=True)),
                ('Shahar', models.CharField(max_length=120, null=True)),
                ('malumot', models.CharField(choices=[('Oliy', 'Oliy'), ("O'rta maxsus/Professional", "O'rta maxsus/Professional")], max_length=30, null=True)),
                ('mutaxasislik', models.CharField(max_length=255, null=True)),
                ('oqishshakli', models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Masofaviy', 'Masofaviy')], max_length=30, null=True)),
                ('oqishturi', models.CharField(choices=[('Shartnoma asosida', 'Shartnoma asosida'), ('Reja asosida', 'Reja asosida')], max_length=30, null=True)),
                ('talimtili', models.CharField(choices=[("O'zbek tili", "O'zbek tili"), ('Rus tili', 'Rus tili')], max_length=15, null=True)),
                ('passportcopy', models.FileField(null=True, upload_to='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('diplomcopy', models.FileField(null=True, upload_to='')),
                ('inn', models.FileField(null=True, upload_to='')),
                ('buyruq', models.FileField(null=True, upload_to='')),
                ('razryad', models.FileField(null=True, upload_to='')),
                ('tuliqligi', models.CharField(choices=[("To'liq", "To'liq"), ('Chala', 'Chala')], default='Chala', max_length=20)),
                ('holat', models.CharField(choices=[('Qabul qilindi', 'Qabul qilindi'), ('Rad etildi', 'Rad etildi'), ("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda")], default="Ko'rib chiqilmoqda", max_length=20)),
                ('sabab', models.TextField(default="Xujjatlar to'liq emas")),
                ('tekshirilganli', models.CharField(choices=[('Tekshirilgan', 'Tekshirilgan'), ('Tekshirilmagan', 'Tekshirilmagan')], default='Tekshirilmagan', max_length=30)),
                ('Hudud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hudud')),
                ('lavozim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lavozim')),
                ('sportturi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sportturi')),
                ('tashkilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tashkilot')),
                ('unvoni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.razryad')),
            ],
        ),
    ]
